### ISSUE TITLE
Why did you divide (event.getX() / 4) 

### ISSUE THREAD

**Issue by lakmalz** [huy-lv/FloodfillAndroid#1]
Hi i have problem. we can get actual point only divided value 4 .i cant understand what is 4.why we are using that value.please give me an answer. sometimes i have change that value for different devices.

**Comment by huy-lv** [comment]
In my layout i define ImageView with absolute size (1000px*800px), it equals 4 times of the bitmap size(250*200) :)) so when get event click, we must divide by 4 :D

**Comment by lakmalz** [comment]
OK Lv, Thank you very much i got your solution ,where should i change in my source.Thank you very much again and again.Have a good life.
